{{- if .Values.ingest.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-core
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "common.fullname" . }}-core
    chart: {{ include "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  stellar-core.cfg: | {{ include "core.config" . | nindent 4 }}
{{- end }}
