{{- if and .Values.ingest.enabled .Values.ingest.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.fullname" . }}-ingest
  namespace: {{ .Release.Namespace }}
  {{- if .Values.ingest.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingest.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  tls:
  - secretName: {{ include "common.fullname" . }}-ingest-cert
    hosts:
    - {{ .Values.ingest.ingress.host }}
  rules:
  - host: {{ .Values.ingest.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "common.fullname" . }}-ingest
            port:
              number: 80
{{- end }}
