{{- if .Values.web.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.fullname" . }}-web-env
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "common.fullname" . }}-web
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ADMIN_PORT: {{ .Values.web.config.adminPort | quote}}
  ALLOW_EMPTY_LEDGER_DATA_RESPONSES: {{ .Values.web.config.allowEmptyLedgerDataResponses | quote}}
  CONNECTION_TIMEOUT: {{ .Values.web.config.connectionTimeout | quote}}
  ENABLE_ACCOUNTS_FOR_SIGNER: {{ .Values.web.config.enableAccountsForSigner | quote}}
  ENABLE_ASSET_STATS: {{ .Values.web.config.enableAssetStats | quote}}
  HISTORY_ARCHIVE_URLS: {{ include "horizon.historyArchiveUrls" . | quote }}
  INGEST: "false"
  MAX_DB_CONNECTIONS: {{ .Values.web.config.maxDBConnections | quote}}
  MAX_PATH_LENGTH: {{ .Values.web.config.maxPathLength | quote}}
  NETWORK_PASSPHRASE: {{ include "horizon.networkPassphrase" . | quote }}
  PER_HOUR_RATE_LIMIT: {{ .Values.web.config.perHourRateLimit | quote}}
  PORT: {{ .Values.web.config.port | quote}}
  SSE_UPDATE_FREQUENCY: {{ .Values.web.config.sseUpdateFrequency | quote}}
  {{ if .Values.web.config.stellarCoreUrl -}}
  STELLAR_CORE_URL: {{ .Values.web.config.stellarCoreUrl | quote}}
  {{- else }}
  STELLAR_CORE_URL: http://{{ template "common.fullname" . }}-ingest-core:11626
  {{- end }}
{{- end }}
